In [ ]:
from google.colab import drive
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
x = ["I am very happy today","No, I do not like the movie"]
y = [1,0]

In [ ]:
tokenizer = Tokenizer(num_words=20)

In [ ]:
tokenizer.fit_on_texts(x)

In [ ]:
sequences = tokenizer.texts_to_sequences(x)

In [ ]:
word_index = tokenizer.word_index
print(tokenizer.word_index)
print("Found %s unique tokens."%len(word_index))

{'i': 1, 'am': 2, 'very': 3, 'happy': 4, 'today': 5, 'no': 6, 'do': 7, 'not': 8, 'like': 9, 'the': 10, 'movie': 11}
Found 11 unique tokens.


In [ ]:
print(sequences)

[[1, 2, 3, 4, 5], [6, 1, 7, 8, 9, 10, 11]]


In [ ]:
max_length = 0
for review_number in range(len(sequences)):
  numberofwords = len(sequences[review_number])
  if((numberofwords)>(max_length)):
    max_length = numberofwords
print(max_length)

7


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
data = pad_sequences(sequences,maxlen=max_length)
y=np.asarray(y)
print(data)
print("Shape of data tensor:", data.shape)
print("Shape of label tensor:", y.shape)

[[ 0  0  1  2  3  4  5]
 [ 6  1  7  8  9 10 11]]
Shape of data tensor: (2, 7)
Shape of label tensor: (2,)


In [ ]:
from tensorflow.keras.models import *
from tensorflow.keras.layers import *

total_words = len(word_index)+1
embedding_dim = 5

model = Sequential()
model.add(Embedding(total_words,embedding_dim,input_length=max_length,name='embedding_layer'))
model.add(SimpleRNN(128,activation='relu',return_sequences=True,name='rnn1'))
model.add(SimpleRNN(256,activation='relu',name='rnn2'))
model.add(Dense(1,activation='sigmoid'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_layer (Embedding  (None, 7, 5)              60        
 )                                                               
                                                                 
 rnn1 (SimpleRNN)            (None, 7, 128)            17152     
                                                                 
 rnn2 (SimpleRNN)            (None, 256)               98560     
                                                                 
 dense (Dense)               (None, 1)                 257       
                                                                 
Total params: 116029 (453.24 KB)
Trainable params: 116029 (453.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
from keras.optimizers import *
opt = SGD(learning_rate = 0.01,weight_decay=1e-5)
model.compile(loss="binary_crossentropy",optimizer = opt,metrics=['accuracy'])
model.fit(data,y,epochs=10,verbose=1)

Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 0.6960 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 20ms/step - loss: 0.6923 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 18ms/step - loss: 0.6896 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 0.6873 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 16ms/step - loss: 0.6853 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 0.6836 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 17ms/step - loss: 0.6819 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 17ms/step - loss: 0.6804 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 24ms/step - loss: 0.6791 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 17ms/step - loss: 0.6780 - accuracy: 1.0000


In [ ]:
embeddings = model.get_weights()
print("Embedding Layer weight shape : ",embeddings[0].shape)
print("Embedding Layer weight : ",embeddings[0])

Embedding Layer weight shape :  (12, 5)
Embedding Layer weight :  [[-0.01665672 -0.03430866  0.02169642  0.0255956  -0.02008986]
 [ 0.03758053 -0.04251179  0.04144001 -0.02545093  0.02802744]
 [-0.01442243  0.03932101  0.01457519  0.0062017   0.02830362]
 [ 0.00227355  0.00998094  0.04991761 -0.00529018 -0.04778458]
 [-0.00859621  0.00822617 -0.01883736  0.04033209 -0.01980667]
 [-0.02864565  0.01143987  0.00179213 -0.04595173 -0.04315553]
 [ 0.04357805 -0.02835813 -0.04155688  0.01078493 -0.03435604]
 [-0.02541331  0.04173858 -0.02135534  0.01512483 -0.02156707]
 [-0.01728323 -0.03908994 -0.04237985  0.02624933  0.01967078]
 [ 0.04871276 -0.0508878   0.02850107 -0.03392233 -0.04501695]
 [-0.02800198 -0.02397641  0.04313796  0.03952325 -0.02575759]
 [ 0.03426393  0.037321   -0.04108738 -0.04398547  0.04528809]]
